version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./nginx/app.conf:/etc/nginx/nginx.conf
    depends_on:
      - my_app
    ports:
    - 80:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432
  my_app:
    image: paulorcvieira/app-dockerizada:latest
    build: .
    depends_on:
      - db
